version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./docker/conf/mysql/:/etc/mysql/conf.d
      - ./docker/data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - "127.0.0.2:3306:3306"

  php-fpm:
    build: ./docker/image/php-fpm
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./docker/conf/php-fpm/php/conf.d/mysqli.ini:/usr/local/etc/php/conf.d/mysqli.ini
      - ./docker/conf/php-fpm/php/conf.d/other.ini:/usr/local/etc/php/conf.d/other.ini
      - ./docker/conf/php-fpm/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    expose:
      - "9001"

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/
      - ./docker/conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/log/nginx/:/var/log/nginx/
    depends_on:
      - php-fpm
      - mysql
    links:
      - php-fpm
    ports:
      - "127.0.0.2:80:80"