version: "2"

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"

  php-fpm:
    build: .
    restart: always
    volumes:
      - /var/www/
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    links:
      - mysql

  nginx:
    image: nginx:alpine
    restart: always
    volumes_from:
      - php-fpm
    volumes:
      - ./docker/conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - "80:80"

volumes:
  mysql-data:
    driver: local